name: CMake

on:
  push:
    tags:
      - 'v*' # включает события push, когда тег начинается с 'v'

permissions:
  contents: write

jobs:
  build_packages_Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Solver
        run: cmake ${{github.workspace}} -B ${{github.workspace}}/build -D PRINT_VERSION=${{github.ref_name#v}}

      - name: Build Solver
        run: cmake --build ${{github.workspace}}/build

      - name: Build package
        run: cmake --build ${{github.workspace}}/build --target package

      - name: Build source package
        run: cmake --build ${{github.workspace}}/build --target package_source

      - name: Make a release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "build/*.deb,build/*.tar.gz,build/*.zip"
          replacesArtifacts: false
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          allowUpdates: true
